/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as ProviderIdImport } from './routes/provider/$id'
import { Route as ClientIdImport } from './routes/client/$id'
import { Route as ProviderServiceIdImport } from './routes/provider/service/$id'
import { Route as CustomerIdImport } from './routes/customer/$id'
import { Route as ProviderPortfolioItemIdImport } from './routes/provider/portfolio-item/$id'
import { Route as BuscarProviderIdImport } from './routes/buscar/provider/$id'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const ProviderIdRoute = ProviderIdImport.update({
  id: '/provider/$id',
  path: '/provider/$id',
  getParentRoute: () => rootRoute,
} as any)

const ClientIdRoute = ClientIdImport.update({
  id: '/client/$id',
  path: '/client/$id',
  getParentRoute: () => rootRoute,
} as any)

const ProviderServiceIdRoute = ProviderServiceIdImport.update({
  id: '/provider/service/$id',
  path: '/provider/service/$id',
const CustomerIdRoute = CustomerIdImport.update({
  id: '/customer/$id',
  path: '/customer/$id',
  getParentRoute: () => rootRoute,
} as any)

const ProviderPortfolioItemIdRoute = ProviderPortfolioItemIdImport.update({
  id: '/provider/portfolio-item/$id',
  path: '/provider/portfolio-item/$id',
  getParentRoute: () => rootRoute,
} as any)

const BuscarProviderIdRoute = BuscarProviderIdImport.update({
  id: '/buscar/provider/$id',
  path: '/buscar/provider/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/client/$id': {
      id: '/client/$id'
      path: '/client/$id'
      fullPath: '/client/$id'
      preLoaderRoute: typeof ClientIdImport
    '/customer/$id': {
      id: '/customer/$id'
      path: '/customer/$id'
      fullPath: '/customer/$id'
      preLoaderRoute: typeof CustomerIdImport
      parentRoute: typeof rootRoute
    }
    '/provider/$id': {
      id: '/provider/$id'
      path: '/provider/$id'
      fullPath: '/provider/$id'
      preLoaderRoute: typeof ProviderIdImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/buscar/provider/$id': {
      id: '/buscar/provider/$id'
      path: '/buscar/provider/$id'
      fullPath: '/buscar/provider/$id'
      preLoaderRoute: typeof BuscarProviderIdImport
      parentRoute: typeof rootRoute
    }
    '/provider/portfolio-item/$id': {
      id: '/provider/portfolio-item/$id'
      path: '/provider/portfolio-item/$id'
      fullPath: '/provider/portfolio-item/$id'
      preLoaderRoute: typeof ProviderPortfolioItemIdImport
      parentRoute: typeof rootRoute
    }
    '/provider/service/$id': {
      id: '/provider/service/$id'
      path: '/provider/service/$id'
      fullPath: '/provider/service/$id'
      preLoaderRoute: typeof ProviderServiceIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/client/$id': typeof ClientIdRoute
  '/customer/$id': typeof CustomerIdRoute
  '/provider/$id': typeof ProviderIdRoute
  '/login': typeof LoginIndexRoute
  '/buscar/provider/$id': typeof BuscarProviderIdRoute
  '/provider/portfolio-item/$id': typeof ProviderPortfolioItemIdRoute
  '/provider/service/$id': typeof ProviderServiceIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/client/$id': typeof ClientIdRoute
  '/customer/$id': typeof CustomerIdRoute
  '/provider/$id': typeof ProviderIdRoute
  '/login': typeof LoginIndexRoute
  '/buscar/provider/$id': typeof BuscarProviderIdRoute
  '/provider/portfolio-item/$id': typeof ProviderPortfolioItemIdRoute
  '/provider/service/$id': typeof ProviderServiceIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/client/$id': typeof ClientIdRoute
  '/customer/$id': typeof CustomerIdRoute
  '/provider/$id': typeof ProviderIdRoute
  '/login/': typeof LoginIndexRoute
  '/buscar/provider/$id': typeof BuscarProviderIdRoute
  '/provider/portfolio-item/$id': typeof ProviderPortfolioItemIdRoute
  '/provider/service/$id': typeof ProviderServiceIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/client/$id'
    | '/provider/$id'
    | '/login'
    | '/buscar/provider/$id'
    | '/provider/portfolio-item/$id'
    | '/provider/service/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/client/$id'
    | '/provider/$id'
    | '/login'
    | '/buscar/provider/$id'
    | '/provider/portfolio-item/$id'
    | '/provider/service/$id'
  id:
    | '__root__'
    | '/'
    | '/client/$id'
    | '/provider/$id'
    | '/login/'
    | '/buscar/provider/$id'
    | '/provider/portfolio-item/$id'
    | '/provider/service/$id'
    | '/customer/$id'
    | '/provider/$id'
    | '/provider/portfolio-item/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/customer/$id' | '/provider/$id' | '/provider/portfolio-item/$id'
  id:
    | '__root__'
    | '/'
    | '/customer/$id'
    | '/provider/$id'
    | '/provider/portfolio-item/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientIdRoute: typeof ClientIdRoute
  CustomerIdRoute: typeof CustomerIdRoute
  ProviderIdRoute: typeof ProviderIdRoute
  LoginIndexRoute: typeof LoginIndexRoute
  BuscarProviderIdRoute: typeof BuscarProviderIdRoute
  ProviderPortfolioItemIdRoute: typeof ProviderPortfolioItemIdRoute
  ProviderServiceIdRoute: typeof ProviderServiceIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientIdRoute: ClientIdRoute,
  CustomerIdRoute: CustomerIdRoute,
  ProviderIdRoute: ProviderIdRoute,
  LoginIndexRoute: LoginIndexRoute,
  BuscarProviderIdRoute: BuscarProviderIdRoute,
  ProviderPortfolioItemIdRoute: ProviderPortfolioItemIdRoute,
  ProviderServiceIdRoute: ProviderServiceIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/client/$id",
        "/customer/$id",
        "/provider/$id",
        "/login/",
        "/buscar/provider/$id",
        "/provider/portfolio-item/$id",
        "/provider/service/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/client/$id": {
      "filePath": "client/$id.tsx"
    "/customer/$id": {
      "filePath": "customer/$id.tsx"
    },
    "/provider/$id": {
      "filePath": "provider/$id.tsx"
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/buscar/provider/$id": {
      "filePath": "buscar/provider/$id.tsx"
    },
    "/provider/portfolio-item/$id": {
      "filePath": "provider/portfolio-item/$id.tsx"
    },
    "/provider/service/$id": {
      "filePath": "provider/service/$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
