/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ProviderIdImport } from './routes/provider/$id'
import { Route as ProviderPortfolioItemIdImport } from './routes/provider/portfolio-item/$id'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProviderIdRoute = ProviderIdImport.update({
  id: '/provider/$id',
  path: '/provider/$id',
  getParentRoute: () => rootRoute,
} as any)

const ProviderPortfolioItemIdRoute = ProviderPortfolioItemIdImport.update({
  id: '/provider/portfolio-item/$id',
  path: '/provider/portfolio-item/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/provider/$id': {
      id: '/provider/$id'
      path: '/provider/$id'
      fullPath: '/provider/$id'
      preLoaderRoute: typeof ProviderIdImport
      parentRoute: typeof rootRoute
    }
    '/provider/portfolio-item/$id': {
      id: '/provider/portfolio-item/$id'
      path: '/provider/portfolio-item/$id'
      fullPath: '/provider/portfolio-item/$id'
      preLoaderRoute: typeof ProviderPortfolioItemIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/provider/$id': typeof ProviderIdRoute
  '/provider/portfolio-item/$id': typeof ProviderPortfolioItemIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/provider/$id': typeof ProviderIdRoute
  '/provider/portfolio-item/$id': typeof ProviderPortfolioItemIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/provider/$id': typeof ProviderIdRoute
  '/provider/portfolio-item/$id': typeof ProviderPortfolioItemIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/provider/$id' | '/provider/portfolio-item/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/provider/$id' | '/provider/portfolio-item/$id'
  id: '__root__' | '/' | '/provider/$id' | '/provider/portfolio-item/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProviderIdRoute: typeof ProviderIdRoute
  ProviderPortfolioItemIdRoute: typeof ProviderPortfolioItemIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProviderIdRoute: ProviderIdRoute,
  ProviderPortfolioItemIdRoute: ProviderPortfolioItemIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/provider/$id",
        "/provider/portfolio-item/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/provider/$id": {
      "filePath": "provider/$id.tsx"
    },
    "/provider/portfolio-item/$id": {
      "filePath": "provider/portfolio-item/$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
